### ISSUE TITLE
Error preventing install with sodium

### ISSUE THREAD

**Issue by nicklanehq** [lprhodes/homebridge-apple-tv#22]
Hi,

I'm trying to install your plugin to test and am getting the following error in terminal when I run the install command. It's struggling with sodium 2.0.3 during install.

Could there be a dependency I'm missing? I've tried installing it separately, but this has had no impact on my ability to successfully install your plugin.

In reading your instructions, I am running NodeJS 9.10.1, which I believe should work.

Any help or guidance is appreciated. Thanks!

---
Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [libsodium] Error 1
/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-15T21_08_58_421Z-debug.log

**Comment by RobertgPatch** [comment]
Try installing sodium package - seemed to work for me

https://www.npmjs.com/package/sodium

**Comment by MrDrache333** [comment]
Allready solved in #5

**Comment by L3x1c0n** [comment]
I'm not able to follow the solution along on Windows... any assistance?

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 install script.

**Comment by MrDrache333** [comment]
On Linux you can install it by install some tools first...
`apt-get install autoconf automake g++ libtool`

**Comment by L3x1c0n** [comment]
Yeah I’m not running my homebridge on Linux though, which is why I specifically asked about Windows... so thanks in advance if you can help on Windows

**Comment by amatrosovas** [comment]
Interested in this as well since I have my homebridge running on windows

**Comment by nicklanehq** [comment]
@MrDrache333 I've tried your solution above for libtool, but I'm now stuck on a new error regarding resolvconf:

Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
Errors were encountered while processing:
 resolvconf
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by safrapetr** [comment]
Hi everyone, I had all the problems above. I solved the problem with installation of sodium-native and after renaming its folder from sodium-native to sodium.
So
1. sudo npm install -g sodium-native
2.cd /home/YOURUSERNAME/node_modules
3. sudo mv sodium-native sodium
4. sudo npm install -g homebridge-apple-tv

Thats it!!!!!

**Comment by mdimai666** [comment]
try
```sudo apt-get install build-essential```
