### ISSUE TITLE
How do I enter the code displayed on my Apple TV?

### ISSUE THREAD

**Issue by DarKOrange75** [lprhodes/homebridge-apple-tv#31]
Hi,

I am running homebridge-apple-tv plugin on my Synology NAS using the docker installation

In your documentation you say that after the TV is discovered I need to enter the code displayed on the screen but how can I do this? The web interface doesn't let me enter anything...

thank you for your help !

**Comment by Pensive** [comment]
This is the same issue as I am facing - someone else managed to succeed by doing this:
[(https://github.com/oznu/docker-homebridge/issues/120)]

But it did not work for me, closing the services left a port open which homebridge-apple-tv needs

```
Error: listen EADDRINUSE :::51826                                               
    at Object._errnoException (util.js:992:11)                                  
    at _exceptionWithHostPort (util.js:1014:20)                                 
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)                  
    at listenInCluster (net.js:1396:12)                                         
    at Server.listen (net.js:1480:7)                                            
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_mod
ules/hap-nodejs/lib/util/eventedhttp.js:60:19)                                  
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap
-nodejs/lib/HAPServer.js:158:20)                                                
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_mod
ules/hap-nodejs/lib/Accessory.js:607:16)                                        
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:128
:16)                                                                            
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:
404:14)                                                                         
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/o
nce.js:16:19                                                                    
    at AppleTVPlatform.accessories (/homebridge/node_modules/homebridge-apple-tv
/node_modules/homebridge-platform-helper/platform.js:42:14)                     
    at <anonymous>                                                              
Disconnected Apple TV's   
```
