### ISSUE TITLE
Installation error on Synology NAS

### ISSUE THREAD

**Issue by sadden3194** [lprhodes/homebridge-apple-tv#35]
hey,

I can't install this plugin. this is the error message:

```
USER: root
DIR: /homebridge
CMD: npm --no-update-notifier install --unsafe-perm --save homebridge-apple-tv@latest


> sodium@2.0.3 preinstall /homebridge/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /homebridge/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [Makefile:62: libsodium] Error 1
/homebridge/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/homebridge/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-12T19_08_44_389Z-debug.log

Command failed. Please review log for details
```

How can I solve it?

**Comment by MrDrache333** [comment]
This issue was solved in Thread #5 :)

**Comment by sadden3194** [comment]
they talked about a missing install of libtool.
But I can't install it with: apt-get install libtool 
> apt-get: not found

**Comment by Mortal11** [comment]
have the same problem with synology nas.
was you solve this?
