### ISSUE TITLE
can't find witch case for change audio source with long press on play/pause

### ISSUE THREAD

**Issue by Arliack** [lprhodes/homebridge-apple-tv#49]
I don't find the good way to add long press for change audio source. 
I try to done the same method on #34  and #37 but this method work only for switch off apple tv (with long press on menu).
Somebody have try to do long press on play/pause button for change the audio source ?
I trying with all sendCommand.js case, with no result...

**Comment by anurag426** [comment]
Please provide info reagrding "How to install this plugin". I have tried many times but still getting sodim issue.

**Comment by Arliack** [comment]
for install this plugin you need install :  npm install -g homebridge-apple-tv
and after modify config.json
and if you have apple tv HD or 4K you need to connect manually your apple tv before launch homebridge.
you can find all specification on : 
https://lprhodes.github.io/homebridge-apple-tv-slate/

 I hope that can help you, if not, can you explain where is your  problem ?

**Comment by anurag426** [comment]
Thanks for the reply @Arliack 
I am getting this error

**Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tavantqa/.npm/_logs/2019-04-12T05_35_24_267Z-debug.log
Administrators-Mac-mini:~ tavantqa$** 

Unable to install 
I have used this command
sudo npm install -g homebridge-apple-tv --unsafe-perm

I tried 
brew install libtool
brew install autoconf
brew install automake

but nothing is working.

**Comment by Arliack** [comment]
I was the same problem, but with lib sodium that work normally.
Can you try to install libsodium before the plug in?

**Comment by anurag426** [comment]
After installing libsodium it started downloading certain things then stopped with this error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tavantqa/.npm/_logs/2019-04-15T05_28_16_556Z-debug.log

Any help would  be appreciated brother

System - Mac with MacOs Mojave 10.14.4

**Comment by anurag426** [comment]
Cant install still showing the error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: node install.js --install
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/tavantqa/.npm/_logs/2019-04-15T05_28_16_556Z-debug.log

I have installed node appletv.
This plugin uses node apple tv. If you have installed this plugin successfully then are you able to run select command.
